### ISSUE TITLE
线上负责人值日制度

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#12]
我建议线上负责人轮流值日，每人一周~
@CodeFalling @semprathlon @GYuGh

**Comment by SimplyY** [comment]
不过那一周得每天都要看看github和博客站。。

**Comment by CodeFalling** [comment]
除了考试或者是不在学校，基本每天都会上github来看的。。不过感觉没必要按固定时间安排，只要是有管理员权限的人都可以处理issue

**Comment by SimplyY** [comment]
但是有个值日的（当周负责人）比较好，，因为以后（协会应该要撑到我们工作以后吧~=，=）不一定有人每天都在线上。。。

**Comment by SimplyY** [comment]
测试了一下，，，只有participate可以assignee=，=

**Comment by NaturalL** [comment]
每天看有没有人投稿麻烦的话，有没有什么通知的方法啊，不行写个程序自动通知呗，哈哈

**Comment by CodeFalling** [comment]
点了`Watch`后Github会有邮件通知，Chrome也有[`Github notify`](https://chrome.google.com/webstore/detail/github-notifier/lmjdlojahmbbcodnpecnjnmlddbkjhnn?utm_source=chrome-ntp-icon)一类的插件

**Comment by SimplyY** [comment]
@NaturalL  学长我发的邮件收到没。。。
@CodeFalling 但是其他人很难确定问题是否解决，然后线上执行者多了后，好多无效信息的感觉=，=，每个人看到投稿都应该会去点开吧（不过我找半天没找到，投稿issue的提醒=，=），要不写一个程序吧？

**Comment by SimplyY** [comment]
@CodeFalling issue里好像是艾特到，或者participants，和当issue需要merge的时候才有邮件提醒？
github的邮件提醒有点乱？（不好自定义），感觉还是写一个，怎么样~~~（虽然我完全不会写。。

**Comment by CodeFalling** [comment]
当然是看到了就点开，毕竟大家是异步的。

邮件通知好像是参与或者watch的人收到，github notify这一类的东西可以提醒是否有未读消息。

还有我现在在用github for Android回复，用邮件直接回复应该也可行
