### ISSUE TITLE
投稿：clean code笔记：序

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#13]
原文 http://simplyy.github.io/2014/07/27/cleancode-0/

**Comment by CodeFalling** [comment]
真是高产~PASS

最近在看`TintBrowser`的源代码，好的代码真不是靠注释的。

同样你用的也是`jekyll`就不用给你规定文件头了，不过提醒下正文中加上

```
* content
{:toc}
```

可以获得一个`Content Table`

**Comment by SimplyY** [comment]
还好。。去年写的笔记，整理的=，=，后面还有至少三四篇高质量的=。=
