### ISSUE TITLE
关于如何利用互联网，搜索，解决基本问题，寻找资源

### ISSUE THREAD

**Issue by NaturalL** [CoderUnion/coderunion.github.io#14]
1.是否谁来一篇讲如何利用互联网，搜索，解决基本问题，寻找资源的文章。
起码有些大一同学还是需要学习的吧。

2.另外是否加强推广，让大家知道有这么个网站。现在学生上听雨少了，是不是都跑百度贴吧上去了？
最好搞个主题明确，页面简洁，结合江大背景的宣传页面，哈哈

**Comment by reverland** [comment]
看到NaturalL兄这么说，忽然觉得我们在做人类历史上有重大意义的事情。

我们在弘扬传统的“黑客文化”。我们传播知识，分享经验，我们用培养和影响我们的文化去影响后来的人，就像当初我们被某些东西影响一样。

我们一群老家伙想要把属于历史的东西传承下去，照射到未来。

哈哈哈，我又扯淡了。

**Comment by SimplyY** [comment]
赞赞赞~~~
不过推广最近不急，，快考前一个月了。。。。。。
等小学期，线上线下结合的第一波宣传开始~~

然后搜索我觉得我做的不够好，因为经常逃避英文= =，不过stackoverflow真心赞，有时还是经常去那找解决办法。
@CodeFalling  我经常问蛇神问题，，然后他轻松地在谷歌里面输入几个英文单词，，就找到我弄了半天都没找到的解决办法，蛇神要不要试一试~~写写

**Comment by NaturalL** [comment]
@reverland 
看得我挺伤感的。
相比那些老师，我们还是很新的，不是老家伙。
我们传播的东西，是经过自己修正的，不管正确与否，和当时培养我们的文化有挺大区别。

我想写一篇文章，但是还不知道怎么写，叫做《我们的信仰和偏见》

**Comment by NaturalL** [comment]
这个网站的建立，是主动去做一些改变，挺好的。
知乎上这个同学就改变了他们学校的氛围。http://www.zhihu.com/question/29930099
这个回答：

>现身说法：
二本（南阳理工学院 ）渣校生，我是本校第一个毕业进入百度的学生，从我们这届开始，到现在即将毕业的大四学生，共四届人中，已有18+个人进入BAT。

>在新生刚来，入学教育起，我们就让他们知道有这么一个OJ，然后找人负责教他们学习，大家都知道大一的新生都是多么的雄心勃勃，多么的努力上进的，我们告诉他们ACM队是多么一个优秀的队伍（自夸），你们多刷些题，如果能在新生组月赛里取得前几名，就可以加入ACM集训队。

>二三流大学的毕业生如何突破企业名校毕业限制条件，获得公平的竞争条件？ - 张云聪的回答
想要应聘百度实习生，校招的时候，面试官比较注重哪几方面的知识的掌握？ - 张云聪的回答

>如果想了解具体我们当时是如何一步步努力过来，使学校学习氛围变好的，可以参考以下答案：

>很多大学建立oj的意义是什么？ - 张云聪的回答
ACM队组建策划书

>ACM并非是唯一一条路，只是我们走了这条路，而这条路又走通了而已。题主可以看看前面那两个通用链接，看看有啥自己能走好的路。

**Comment by SimplyY** [comment]
以后江大四届说不定还不止18+，在我们的努力传承黑客文化下~~
毕竟生源肯定比二本好~

**Comment by SimplyY** [comment]
关于搜索我有一个好主意，题目定为快速学习。

因为搜索和看书是截然不同的学习方式，需要截然不同的技巧，来达到快速的在茫茫网页中找到what you want learn，而且通常搜索的来的东西是碎片化的，快速的将碎片化的东西理解非常重要（因为往往我们debug的时候没那么多空余的时间），也就是说我们需要在有限的时间内快速消化，而这需要一定的技巧，我认为我很缺乏。。。无论是快速找到，还是消化。。

然后除了，搜索这种情景，还有对自己写的代码的总结重构和debug的时候，其实也是在学习，我觉得这方面也需要

所以另开一个issue~~大家一起聊聊快速学习，然后我整理成一篇文章出来~~

**Comment by SimplyY** [comment]
日后在讨论区讨论把

**Comment by SimplyY** [comment]
已归档
