### ISSUE TITLE
有关“快速学习”的讨论

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#19]
@xen0n 
@NaturalL 
@CodeFalling 
@NaturalL

**Comment by SimplyY** [comment]
#14

**Comment by SimplyY** [comment]
>他们会突然说一个令你完全摸不着头脑的东西并且征求你的想法，但是这个想法是在他们看到了／听到了／接受了某项新的信息以后，在大脑中逻辑思考了几步之后给出的问题。
在这个描述里面，天才大脑的「转数」似乎比普通人快几十倍，即在你还没能理解一个信息的时候，他们已经能完成了几步的逻辑思考。但实际上从「工作记忆」的角度看，人与人之间的差异绝不可能有这么大。那么差别在哪呢？就是「信息碾压能力」，面对同样的信息，天才能够快速地抽取出其中最核心的部分，然后进行快速的推导。而普通人，却还受困于纷繁复杂的信息细节中无法自拔。
在今天的互联网时代里，人们每天都在接触着过剩的信息，就像浸在一个大浴缸里洗「信息泡泡浴」（脑补出香艳美女的拉出去砍了）。从智力的角度讲，人们反而可能变笨了，因为这么多的信息似乎只能让他们疲于奔命，不断地去被动地接受。而这个社会中，处于智力金字塔顶端的人，却不是这样，他们主动出击，就像一个具有鹰一样锐利的双眼的猎人一样，去采集真正有价值的信息，再进行无情的碾压，然后把最关键或最有挑战的部分放到工作记忆中进行「运算」，即工作记忆这块「好钢」总是能用在刀刃上（当然其实选择的过程、碾压的过程也需要工作记忆，我这里强调的是，经过这一系列快速迭代的过程后，最终工作记忆得以应用在一个系统中最关键的成分上；而那些洗「信息泡泡浴」的人，他们永远处理的是某一个局部、某一个泡泡）。更要命的是，从长期来看，他们会把习得的知识进行充分的模块化处理，压缩成高密度的一块块的干块，就像能量块之于汽车人，当汽车人饿的时候，只要一吃能量块，立马就生龙活虎。
这真是一个「恐怖」的现实：如果上述的对比场景重复成百上千次之后，人与人之间的差距就会大得超过你的想象。


其实我想问的是这个，采铜的书里看到的，然后我觉得蛇神已经有这种能力，感觉我被碾
@CodeFalling

**Comment by SimplyY** [comment]
@xen0n 
@reverland

**Comment by CodeFalling** [comment]
不要吹我@_@我能力有限

私以为所谓的信息提炼也是通过训练得到的，就像熟悉Windows的用户能够在一堆假的「下载」中以最快的速度找到正确的那个一样。一个训练有素的人也能从google结果快速的找到stackoverflow（233），从github快速筛出有趣的项目，从文档中快速找到结果。

你看我期末复习就很无助，因为没有有效的训练（平时不复习），缺乏相关的知识网络（对数学方面知识了解不多）。
