### ISSUE TITLE
能实现博客站能订阅，然后新文章自动推送到邮箱的功能吗

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#22]

**Comment by SimplyY** [comment]
@NaturalL 学长每次能很早就评论文章是怎么做到的，，

**Comment by SimplyY** [comment]
用pyqt写成一个客户端怎么样，qt是不是比较容易跨平台。

只是想实现分类下订阅，然后邮件推送觉得不好。作为单独一个轻量级阅读客户端不错感觉。

**Comment by CodeFalling** [comment]
IFTTT+github webhook+gmail

**Comment by xen0n** [comment]
webhook这么卧槽的功能亏你们想得出来... 我微雨框架里有个webhook实现框架 (之前听雨的部分组件和之前我做的数媒学院网站都是用的这个组件实现的自动更新), 接到push之后看看_posts里头有没有变, 变了就往任务队列加一个任务, 异步推送 (为了及时响应github端), 看看你们能不能做

**Comment by xen0n** [comment]
任务队列的话我应该可以架, 听雨服务器上我之前架过一个redis (当时给新站用的), 现在还能用, 有需要可以找我~ 当然你们用sae这种自带任务队列的服务也不是不可以(

**Comment by reverland** [comment]
我猜Natural是收到了github的邮件，可以直接在邮件回issue

**Comment by SimplyY** [comment]
话说我想写一个跨平台的客户端了，加上众多功能，包括博客站选择性的订阅，阅读，更方便的投稿，账号系统，私信等，像以前听雨是方面太广，我想做一个专门针对程序员们的站。(写客户端的原因是，我不会web，，，)，

**Comment by CodeFalling** [comment]
和客户端对应的是前端，后端还是要写，所以总是逃不开web。

所以说你想写的其实是个网站……

**Comment by SimplyY** [comment]
想了一会还是觉得web好- -QAQ
