### ISSUE TITLE
利用issue列表建立问答系统

### ISSUE THREAD

**Issue by CodeFalling** [CoderUnion/coderunion.github.io#23]
参照https://github.com/android-cn/android-discuss

issue列表本身就可以作为一个问答系统试用，通过watch和单个issue下的`subscribe`订阅通知，非常合适。我们可以单独开一个repo做此用，大家意下如何

**Comment by NaturalL** [comment]
不错

**Comment by reverland** [comment]
这年头，拿github做博客做网站做图床做论坛做什么的都有。。。

**Comment by SimplyY** [comment]
666，点个赞，考完试一起弄~

**Comment by SimplyY** [comment]
准备写一个web上的
