### ISSUE TITLE
投稿: 我是怎样搭建我的博客站的

### ISSUE THREAD

**Issue by xen0n** [CoderUnion/coderunion.github.io#24]
http://blog.xen0n.name/2015/05/11/making-of-this-blog/

![开心](http://tb2.bdstatic.com/tb/editor/images/face/i_f07.png?t=20140803)

<s>是不是写得太难了囧刚刚ds表示看不懂</s>

**Comment by CodeFalling** [comment]
Pass

原来是自己撸了一个静态生成器，考虑单独整理成一个项目肿么样，如果好用的话还可以安利一下。在这里留一下文章markdown格式的地址吧（虽然我知道在哪-。-）。

一直在考虑之前的投稿方式太麻烦，打算加入在issue里直接递交markdown文档的方式的，不过快考试了没时间整理。

**Comment by xen0n** [comment]
好好好

[地址](https://github.com/xen0n/xen0n.github.io/blob/master/_posts/2015-05-11-making-of-this-blog.md) 属性的格式我故意弄得像Jekyll一样233

回去准备PR...

**Comment by xen0n** [comment]
话说直接提交markdown的话用fenced code block不就好了嘛

```markdown
    ```markdown
    TODO
    ```
```

是不是

**Comment by xen0n** [comment]
额, 直接提交的话貌似如果原文里就有 fenced code block 会造成转义问题... 嘛, 不知道能不能转义 (我markdown渣

**Comment by CodeFalling** [comment]
可以直接发markdown的说，然后管理员点下`edit comment`就能看到，反正怎么方便怎么来。和大牛说话就是省力，PR都发好了

**Comment by reverland** [comment]
膜拜气体～

**Comment by NaturalL** [comment]
好
又看到一些新名词

**Comment by xen0n** [comment]
@reverland 额，我只是不想让下划线延长到100%宽度。。这个效果当时没想到，那做起来就蛋疼了（hX里头要套一层才行貌似）我想想怎么改。。。。。

话说gulp简单啊，就是个管道而已。。。你想学什么0 0

**Comment by reverland** [comment]
@xen0n ლ(╹◡╹ლ)我要学习成为气体这样的大神
