### ISSUE TITLE
投稿：图解数据挖掘是“神马”

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#27]
http://mp.weixin.qq.com/s?__biz=MjM5MDAxNjkyMA==&mid=207102420&idx=3&sn=832c3a9709b1b1014f4d0d264061ce99&scene=1&from=singlemessage&isappinstalled=0#rd

**Comment by SimplyY** [comment]
班主任投稿的，介绍的还不错，我来把原文转为md格式把

**Comment by semprathlon** [comment]
图片外链挂了

**Comment by SimplyY** [comment]
e @semprathlon
