### ISSUE TITLE
投稿：一波三折而又苦尽甘来的二分查找的算法应用

### ISSUE THREAD

**Issue by semprathlon** [CoderUnion/coderunion.github.io#29]
文章地址：http://blog.semprathlon.net/archives/312

**Comment by CodeFalling** [comment]
ACM文章谁来审~

话说目前还没有`mathjax`支持，谁来把这件事做了，或者等考试结束

**Comment by CodeFalling** [comment]
才反应过来ACM方面的文章就是你自己审，已经把你权限提升了，仿照其他文章的方式开PR吧
