### ISSUE TITLE
【重要】求修改建议，给以后每届的大一新生学编程入门参考

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#37]
http://simplyy.github.io/2015/05/02/code-start-tips/

这篇文章我需要迭代

给大一新生学编程入门参考

大家看完提提意见

**Comment by SimplyY** [comment]
@NaturalL 
@CodeFalling 
@CoderUnion/member

**Comment by CodeFalling** [comment]
把黑我的那一段去了，看书囫囵吞枣只是我个人习惯，不一定好😑

**Comment by xen0n** [comment]
这不就一篇膜蛇神的文章么233其实还好啊我是想自己也写一篇来着，每个人都写一篇

**Comment by CodeFalling** [comment]
严肃的说这样强行膜没有意义，何况我这水平还不值得膜，大家认真整理下说不定还能写出点真有用的，例如http://zhuanlan.zhihu.com/xiao-jing-mo/19959253这种

**Comment by xen0n** [comment]
（我是想自己也写一篇（入门参考），不是想写一篇（膜蛇神的文），囍

**Comment by xen0n** [comment]
（其实干货还是有的，把膜拜的内容单独提出来做个case analysis或者干脆去掉会更好

**Comment by CodeFalling** [comment]
知道-。-，我就是说还是尽可能整理出一些相对客观中立的干货出来

**Comment by SimplyY** [comment]
@CodeFalling  然而。。由于没装chrome的github'插件，才看到。。干活还是中立的把，就黑了一句而已233333

**Comment by SimplyY** [comment]
已将“蛇神”改成“大牛”

**Comment by CodeFalling** [comment]
，，不黑不行么，，这样膜来膜去的样子开开玩笑还行，不适合拿到台面上


而且对新手的指导要谨慎，他们的知识面不够广，可能会产生一些片面的认知

**Comment by NaturalL** [comment]
哈哈

**Comment by semprathlon** [comment]
是不是可以推出“技能树”作为概念模型呢？

**Comment by SimplyY** [comment]
极有道理，之前其实线讨论不是谈到过，由各领域的版主推出jncoders线上的“成就徽章”，然后审核通过即授予。

其实徽章是可以当做技能树的一个一个的节点的。

不过现在就用俩todo了

- [ ] 确定各领域版主
- [ ] 制作各领域技能树
- [ ] 设计徽章，以及细化审核题目和方式

**Comment by SimplyY** [comment]
#41
