### ISSUE TITLE
CoderUnion 已改名jncoders

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#38]
以后重写的博客站、讨论区、问答区都用此名字吧

**Comment by NaturalL** [comment]
咋改名了
我的名字和你的好像啊，格式一模一样
过段时间来投稿

**Comment by SimplyY** [comment]
1. 因为想做成社区了（分层次的那种，博客站高阶，问答讨论区中低阶），这个名字对新入门的coders更具亲和力吧。
2. 地域性更强jncoders可能更适合在校生校友。

我觉得这里的issue好多都可以整理到问答区和讨论区，暑假把新版敲完，我来弄弄各种的搬迁。

**Comment by SimplyY** [comment]
又改回来了。。。
