### ISSUE TITLE
投稿：[Visual Studio]Windows窗体应用程序代码中的[STAThreadAttribute]是什么?  

### ISSUE THREAD

**Issue by semprathlon** [CoderUnion/coderunion.github.io#4]
博文地址：http://blog.semprathlon.net/archives/270

**Comment by CodeFalling** [comment]
Pass

更多的排版意见和建议我需要仔细读一遍，明天回复

**Comment by CodeFalling** [comment]
仔细读了一遍，这篇文章大部分内容都是引用，那么是要推荐[COM线程模型详解 ](http://blog.chinaunix.net/uid-24862988-id-3799415.html)的文章么.

如果这不是讨论的主题，建议提取引用内容中对主题有用的东西，并且适当增加主题相关的论述。

**Comment by xen0n** [comment]
跟标题相关的就文章开头一段代码。。。我+0 on this

**Comment by NaturalL** [comment]
我觉得这种具体的知识点没必要放上去，以下几项就行了：
    原创文章 + 方向路线介绍（感受，学习方法） + 书籍推荐（理论） + 网站技术推荐（知识面、视野） + 项目推荐（实践）

下面的不能放上去：
    受众太窄
    遇到问题一google一百度就行的

一个学校，人不会很多。文章一定要精，实在、接地气，解困惑，拓视野。

**Comment by SimplyY** [comment]
受益匪浅，已采用。@NaturalL

**Comment by xen0n** [comment]
嗯。。。

我觉得吧，这种非常有针对性的文章，可以不必非得全文转啊，以**阅读清单**形式存在应该也行

当然这篇文章的话要不要录用还是看你们啦（

**Comment by NaturalL** [comment]
哈，这位同学来投稿很好，说明他是关心这个网站的。
这个网站挺好的，我也关心。
以前挺多人上听雨，我从听雨上知道了 @xen0n  和 reverland，他们是很值得学习的人，而且我也感受到了他们对计算机的热情，让我很受鼓舞。

**Comment by SimplyY** [comment]
学长@NaturalL  其实@reverland 也点了star的~~~可以艾特~

**Comment by reverland** [comment]
怎么感觉像在做phrack = =

**Comment by SimplyY** [comment]
@reverland  恩，，，江大版，，基础版，现在新增了一个分类“开源项目”~，学长以后有空也可以来写写文章嘛~

**Comment by reverland** [comment]
@SimplyY 渣。。。捂脸。。。

**Comment by NaturalL** [comment]
@reverland  phrack? 这个我不知道，学习了。圈子不同关注点不同，接触的东西就不同，有些东西自己就接触不到。
这个网站就作为江大学生交流、发现知识的地方呗

**Comment by NaturalL** [comment]
@reverland  先不论你渣不渣，你身上肯定有值得别人学习的地方，而且，我认为一个对计算机有热情，好钻研的人，总有值得学习的地方。

**Comment by SimplyY** [comment]
@NaturalL 学长正能量满满~~

当初这个CoderUnion也是知乎上我的一篇正能量的回答而建立的。
想起来我之前说的一句话。
> 学编程最有趣的事情之一，就是碰到志同道合的伙伴嘛，我们提供一个平台，然后小伙伴们在江大就很容易聚起来了~

@reverland  学长就不要推辞了~

不过忙的话是不用天天或者每星期来弄的，博主也是自己写博客的同时，突然觉得放到这里很不错，就PR到这里的嘛。所以即便几个月才写一篇博文我们也是会非常欢迎的，即便是一点点力量的汇集，多了，所产生的力量是很厉害很厉害的~~

**Comment by xen0n** [comment]
？这标题改得。。。什么意思

**Comment by SimplyY** [comment]
@xen0n  额，我只是描述了一下，issue里讨论了，，，投稿的规范化要求和协会的力量的来源。。

**Comment by xen0n** [comment]
我是不懂为什么要写在标题里... 你是想提醒大家这里有讨论? 那样的话你在另外那个issue里用 #4 这样引用过来不就行了嘛

**Comment by SimplyY** [comment]
有道理 我改改，其实我github issue用的不多=，=，不怎么会
