### ISSUE TITLE
社区发展TODO

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#41]
### 开发

- [ ] 新的讨论区
- [ ] 新的问答系统

### 短期
- [ ] 迭代开发，实名邀请注册
- [ ] 搜集编程学习资料 #39 

- [ ] 在讨论区讨论各领域的技能树
    - [ ] 确定各领域（使用tag）版主
    - [ ]  制作各领域技能树
    - [ ] 设计相应技能点的徽章，以及细化**审核题目和方式**

### 长期
- [ ] 当线上氛围不错时，将开发者大会和技术交流会举行，并规定为**定期举行**的方式，就行谷歌苹果的一年一度的开发者大会一样。
- [ ] 每年培养和选出新的最佳社区贡献者当负责人，选出新的版主副版主等，也就是换届。

**Comment by wubugui** [comment]
搞个独立站什么的比较好，github上开issue对于新生来说门槛太高了，我也是刚刚才发现你们在这里开issue讨论东西的。。。
新生入学啥的去招个新和学校商量下做个友链啥的大法好啊。
早点认识你们多好，就可以瞎参和一下了，现在都是要毕业的人勒TAT

**Comment by CodeFalling** [comment]
@wubugui 其实一直有这个计划来着，只是因为我效率较低进度比较慢，最近会在开发。
学长毕业了也正好可以给我们传授点经验，现在正缺能指点我们的人-。-

**Comment by SimplyY** [comment]
就主力弄 issue 和 qq 群吧。
