### ISSUE TITLE
web前端技能树的讨论

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#42]
我读http://www.zhihu.com/question/29448457/answer/45411615 之后总结了：

1. 计算机的基本功
	- 算法（需要刷题）
	- 编译原理
	- 操作系统
	- 计算机网络
2. 深入掌握web前端理论知识
	- 看web前端的著作
	- 看web前端的博客
	- 看文档
3. 大量的web前端实践
	- 读大牛的代码
	- 做前端项目（重要）
	- 懂后端
4. 在网上的自主学习能力
	- 谷歌搜索能力（最好学会用英文搜索）
	- 阅读英文文档能力（stackoverflow、各类框架文档）
	- 学习最新前端技术（前端技术迭代快，出书的少，需要网上自学）

感觉需要过来人教教，指导，因为我不会前端啊，，

@xen0n 
@CoderUnion/member

**Comment by semprathlon** [comment]
对HTML5的感知？API的应用？对Node.js的了解？

**Comment by SimplyY** [comment]
来自蛇神

![image](https://cloud.githubusercontent.com/assets/8455579/8599280/165d4b88-2692-11e5-80c6-dfa97f0a0b76.png)

**Comment by CodeFalling** [comment]
我一直认为所谓的某个方向的**技能树**还是很难有个定论，尤其是我们在本身就不甚了解的情况下。但是可以引用一些比较好的文章，书籍招聘等作为一个**参考**，兼听则明。

ps:上面的图是在V2EX随手截的，市场的需求也可以作为一个参考点

**Comment by SimplyY** [comment]
![](http://www.w3cplus.com/sites/default/files/blogs/2015/1506/webfe.jpg)

**Comment by reverland** [comment]
https://github.com/JacksonTian/fks

给上图加上引用

**Comment by SimplyY** [comment]
winter(阿里前端主管写的)阿里招聘要求
![](http://7q5a8u.com1.z0.glb.clouddn.com/474ebf35gw1et1h1ukl2aj20hh136ad2.jpg)

**Comment by reverland** [comment]
阿里啊，明明比较看重项目经验。

根本不会在乎这些

**Comment by SimplyY** [comment]
已归档
