### ISSUE TITLE
推荐好的rss源

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#44]
用rss来订阅技术博客再好不过，使用rss的在这里写写你推荐的好的rss源吧

关于RSS的说明和如何使用的摘录 ,http://www.zhihu.com/question/19580096

> 支持RSS是一种美德。

> 什么是RSS？

> RSS（Really Simple Syndication，简易信息聚合）是一种描述和同步网站内容的格式。
你可以认为是一种定制个性化推送信息的服务。它能解决你漫无目的浏览网页的问题。
它不会过时，信息越是过剩，它的意义也越加彰显。

> 为什么需要RSS？

> 网络上充斥着大量的信息垃圾，我的体会是：每天摄入了太多我根本不关心的信息。
我希望让我关注的信息主动来找我 ，且这些信息都是我需要的，这就是RSS的意义。

**Comment by SimplyY** [comment]
my opml
<?xml version="1.0" encoding="UTF-8"?>

<opml version="1.0">
    <head>
        <title>伟 subscriptions in feedly Cloud</title>
    </head>
    <body>
        <outline text="news" title="news">
            <outline type="rss" text="要闻--华尔街日报" title="要闻--华尔街日报" xmlUrl="http://chinese.wsj.com/gb/rss01.xml" htmlUrl="http://cn.wsj.com"/>
            <outline type="rss" text="知乎每日精选" title="知乎每日精选" xmlUrl="http://www.zhihu.com/rss" htmlUrl="http://www.zhihu.com"/>
            <outline type="rss" text="鲜果日志" title="鲜果日志" xmlUrl="http://feed.feedsky.com/xianguoblog" htmlUrl="http://blog.xianguo.com"/>
            <outline type="rss" text="Rocky Sand Studio » News" title="Rocky Sand Studio » News" xmlUrl="http://rockysandstudio.com/tag/news/feed" htmlUrl="http://www.rockysandstudio.com"/>
            <outline type="rss" text="36氪" title="36氪" xmlUrl="http://www.36kr.com/feed" htmlUrl="http://36kr.com"/>
            <outline type="rss" text="知乎日报" title="知乎日报" xmlUrl="http://feeds.feedburner.com/zhihu-daily" htmlUrl="http://news-at.zhihu.com/api/4/stories/latest?client=0"/>
        </outline>
        <outline text="code blog" title="code blog">
            <outline type="rss" text="EFE Tech" title="EFE Tech" xmlUrl="http://efe.baidu.com/atom.xml" htmlUrl="http://efe.baidu.com/"/>
            <outline type="rss" text="代码家" title="代码家" xmlUrl="http://blog.daimajia.com/feed/" htmlUrl="http://blog.daimajia.com"/>
            <outline type="rss" text="酷 壳 - CoolShell.cn" title="酷 壳 - CoolShell.cn" xmlUrl="http://coolshell.cn/feed" htmlUrl="http://coolshell.cn"/>
            <outline type="rss" text="云风的 BLOG" title="云风的 BLOG" xmlUrl="http://blog.codingnow.com/atom.xml" htmlUrl="http://blog.codingnow.com/"/>
            <outline type="rss" text="阮一峰的网络日志" title="阮一峰的网络日志" xmlUrl="http://www.ruanyifeng.com/blog/atom.xml" htmlUrl="http://www.ruanyifeng.com/blog/"/>
            <outline type="rss" text="MacTalk-池建强的随想录" title="MacTalk-池建强的随想录" xmlUrl="http://macshuo.com/?feed=rss2" htmlUrl="http://macshuo.com"/>
        </outline>
    </body>
</opml>

**Comment by CodeFalling** [comment]
https://github.com/Gracker/Rss-IT

**Comment by SimplyY** [comment]
程序员大法好，爬虫大法好，微信公众号可以生成rss， http://www.zhihu.com/question/21288524

**Comment by gy134340** [comment]
###rss，懂了
