### ISSUE TITLE
[投稿] 一些并发编程的学习

### ISSUE THREAD

**Issue by NaturalL** [CoderUnion/coderunion.github.io#45]
http://www.jianshu.com/p/70cd64dca48e

惭愧呀，距离上次好久了，总感觉写不出啥，这次算是引入一个话题吧

**Comment by CodeFalling** [comment]
我们作为维护者才是惭愧了-。-，因为考试和数学建模一类的事情耽误了不少时间，感谢学长支持。
我们需要**文章的markdown格式**，你可以**发在这个issue里，或者贴在哪发链接**也可以，后面的我帮你处理。

**Comment by SimplyY** [comment]
我们不是在弄新的功能（讨论区和问答区）嘛，然后csapp看得太慢了，笔记不好做。

**Comment by NaturalL** [comment]
@CodeFalling  
https://raw.githubusercontent.com/NaturalL/naturall.github.com/master/_posts/2015-07-25-something-about-learning-concurrent-programming.md

**Comment by CodeFalling** [comment]
已发
http://coderunion.github.io/2015/07/25/something-about-learning-concurrent-programming/
