### ISSUE TITLE
渲染，模拟，以及游戏引擎

### ISSUE THREAD

**Issue by wubugui** [CoderUnion/coderunion.github.io#46]
这篇文章是面向新人的，老鸟无视之。

本文主要讲述渲染，模拟，以及游戏引擎等东西，讲的都是介绍界级别的东西很简单，并且只讲述一些教科书上不讲或者被初学者所忽视的东西多数来自笔者的学习实践经验，有误的地方请指出。知识细节就不多讲了，书，paper，google到处都是，大家自己看，文中笔者会给出大量的参考文献。

# 渲染
渲染就是把三维的物体或者场景描述转化为一副二维图像。

渲染分为离线渲染和实时渲染。最先有的是离线渲染，最开始他是为电影服务的，开始的资料可以参考到卢卡斯影业的《星球大战》那批做特效的人显然就是现在大名鼎鼎的工业光魔（Industrail Light & Magic）。

后来的实时渲染的很多技术都来自离线渲染，并且都落后离线渲染很多年。实时渲染的区别很明显，是在可接受视觉范围内的效率。

现在有很多游戏和公司号称电影级实时渲染，这都是夸张的说法，同一个时代的实时渲染无论怎么牛逼都会被电影甩出几十条街（当然你过你说国产的《汽车人总动员》，当我没说）。

可能很多少年接触渲染都是从游戏开始的，而游戏都是实时渲染，所以很多人接触渲染都是接触的实时渲染，然而实时渲染的很多东西几乎都是渲染中的trick， 所以从实时渲染开始学习渲染实为不妥。但是笔者总是见到有初学者提问问`"学习OpenGL好还是DirectX好/学DirectX9好还是11好/OpenGL应该学哪个版本"`这样的问题。实际上在学习渲染的时候最开始应该学习的不是OpenGL也不是DirectX，这些东西从某种角度讲，并不是渲染的全部，甚至和学习渲染没有几毛钱的关系，因为你脱离了这些东西照样可以学习渲染。在初学渲染的时候一定不能被这两个东西带偏了路子，遮挡了看见广大世界的视线。

离线渲染比较复杂，我们讲讲实时渲染，作为例子我们来说实时图形的管线。

> 如果你对离线图形感兴趣，请参考[简单介绍离线渲染和电影](http://www.opengpu.org/forum.php?mod=viewthread&tid=4471)以及[pixer的一些paper](http://graphics.pixar.com/library/)，参考的入门书籍包括[pbrt](http://www.pbrt.org/)以及其中的further reading等等,另外这个领域的[鼻祖论文](http://www.opengpu.org/forum.php?mod=viewthread&tid=4665&extra=page%3D1)。

## 实时渲染管线
图形渲染的管线也就是图形渲染的流水线，一个流水线是一序列可以并行和按照固定顺序进行的阶段。 每个阶段都从它的前一阶段接收输入，然后把输出发给随后的阶段。就像一个在同一时间内，不同阶段不同的汽车一起制造的装配线，传统的图形硬件流水线以流水的方式处理大量的顶点、几何图元和片段。

我们考虑管线就是工厂里的流水线，那么很明显： 在渲染管线中是最慢的阶段决定整个渲染的速度。

我们一般使用吞吐量（throughput）来描述一个阶段的处理速度，而不是帧率。因为帧率会受到设备更新的限制而导致实际速度比帧率所标示的更慢。

一个例子：

> 假设一个设备为60赫兹，这意味着这个设备16.666666ms刷新一次，这时恰好有一管线阶段花费了62.5ms执行完成，由于63大于16.666666_3，小于16.666666_4，所以他实际上想要最终完成工作必须等待下一次设备刷新。所以真实的执行时间折算下来其实不止62.5ms而是趋近于66ms。当然，如果关闭了垂直同步就另当别论了。

一个渲染管线可以粗略的按照执行顺序分成三大阶段：
1. 应用阶段
2. 几何阶段
3. 光栅阶段

这些阶段又可以细分为更多的子阶段，注意这些都是功能性的分配，在实现上为了效率等因素往往会合并一些阶段或者拆分一些阶段等等。

下面是一张图：

![](http://images.cnitblog.com/blog/322020/201503/021729497233272.png)

### 应用阶段
这个阶段的目标就是为几何阶段产生合适的图元数据，一般来说，很多工作都在这个阶段完成，诸如碰撞检测、动画、输入、当然还有一些加速管线的算法，比如层次视椎剔除（hierarchical view frustum culling）等等。

### 几何阶段
几何阶段集中于逐多边形操作和逐顶点操作。
1. **模型-视图转换**：模型坐标-->世界坐标-->相机坐标
2. **顶点着色**：计算着色方程根据材质数据（位置、法线、颜色、其他着色方程需要的数据等等）决定光照效果，结果可以是（颜色、向量、纹理坐标或者其他种类的着色数据）。通常在世界空间中发生、有时候会把相关实体转换到其他空间，并在此空间进行计算。
3. **投影**：略
4. **裁剪**：在单位立方体之外的基元被舍弃，而完全在单位立方体之内的基元被保留；相交的基元则进行剪切，生成新的顶点，而老的被丢弃。
5. **屏幕映射**：只有已裁剪的部分才会被传递给屏幕映射，坐标仍然是3维的。将x/y转换成平面坐标。转换后的x/y叫做屏幕坐标。有一个注意事项是：如何把浮点数映射到像素以及某些系统之间屏幕做坐标原点的问题。

### 光栅阶段
1. **建立三角形**：计算三角形表面差值等数据，这个数据将会用于下一阶段的扫描转换，以及几何阶段生成的各种着色数据的插值。
2. **遍历三角形**：检查每个被三角形覆盖了中心的像素，并为何三角形重叠的部分生成片段。查找那些在三角形之内的像素或者采样的过程叫做扫描转换。生成的每个在三角形内的片段都是根据三角形顶点插值出来的，这些片段的数据包括深度以及各种来自几何阶段的着色数据。
3. **像素着色**：插值完毕的着色数据输入其中，执行所有的逐像素着色操作，并将一个或者多个颜色传递给下一个阶段。纹理技术也在此阶段实现。
4. **合并**：每个像素的信息被存储在颜色缓冲中，它是颜色的矩形数组（每个颜色拥有红、绿、蓝三部分）。合并阶段负责将着色阶段生成的片段颜色和当前缓冲中存储的颜色进行组合。并且包含可见性检测、模板操作等等。

--------------------------------------------------------------------------------

说到这里，相信你对实时渲染管线已经有了一定的认识，实时渲染管线其实很简单，每一个步骤都是为了能够更加方便的产生出渲染结果。

另外实时渲染管线的发展来看，有两种，一种是固定管线，另外一种是可编程管线。

所谓**固定管线**就是上面所讲述的所有的功能都是固化到硬件中的，最多最多也就是可以配置，并不能大面积的自定义。 而所谓**可编程管线**就比较牛逼了，上面讲到的大部分阶段都是可以使用程序控制的，我们把这些控制管线的程序叫做shader，这大大增加了灵活性。现代的图形API已经演化成了没有Shader就不能运行的程度。

对于初学者来说，可能会觉得很麻烦，画个三角形，要写一大堆代码，掌握一堆知识。大家都想一行诸如"draw_rect(...)"就画一个矩形，这样多好，但是这样的东西功能有限，到了大规模绘制，复杂绘制的时候就力不从心了。所以为了今后渲染大场景着想，还是要忍受这样的东西。

有的初学者包括某些任课教师为了避免这样的复杂性使用老掉牙的固定管线来初学，这样看似避免了繁琐的细节，把焦点拉到了主要的绘制算法上，实则是丢失了对渲染的完整影响，容易造成错觉对可编程管线形成抵触情绪，显然这样子是不好的。笔者初学Opengl的时候就是这样，用惯了固定管线的gl，对可编程管线产生了抵触，觉得很浪费时间，感觉写两个shader无比难，知道非写不可。

其实说起来，可编程管线并不困难也不烦杂。对于一个简单的程序，我们可以简单地把他归为如下步骤，以OpenGL为例：
1. 编写顶点Shader，片元Shader代码。
2. 在宿主程序中初始化API环境
3. 读取编译链接Shader代码
4. 告诉管线使用某组Shader
5. 调用drawcall渲染

看起来很简单，实际上就是这么简单，那些shader的代码对于简单的helloworld都是一样的。

接下来，我们来把各种shader和上面所说的管线阶段对应起来：

 **vertex shader**：模型-视图转换，顶点着色，投影

 **geometry shader**：操作图元顶点（primitive概念看下方）----图元着色、销毁/创建图元

 **pixel(fragment) shader**：像素着色

 关于实时渲染更多的内容可以参考：[《Realtime rendering 3rd》](http://book.douban.com/subject/3213439/)  更多的API知识书籍很多，OpenGL必然是[蓝宝书](http://book.douban.com/subject/5273949/),不推荐一上来就看[红宝书](http://book.douban.com/subject/4311129/)。DirectX的东西推荐入门后看[官方文档](https://msdn.microsoft.com/en-us/library/windows/desktop/dn899121%28v=vs.85%29.aspx),另外DX11一下的版本就不要学习了，OpenGL尽量学习最新的版本。

 最后必须要说一下，如果你想要搞图形，笔者不推荐一上来就学习这些API，笔者推荐你按顺序看下面这些书来入门，这样你可以有一个全面的认识和扎实的基础：
- [Computer Graphics: Principles and Practice (3rd Edition)](http://www.amazon.cn/Computer-Graphics-Principles-and-Practice-Hughes-John-F/dp/0321399528)
- 这本书使用WPF来作为图形API，将OpenGL从你的世界中移除了，你再也不会走上歧途了，可喜可贺。
- [Physically Based Rendering, Second Edition: From Theory To Implementation ](http://www.amazon.cn/Physically-Based-Rendering-Second-Edition-From-Theory-To-Implementation-Pharr-Matt/dp/0123750792/ref=pd_sim_14_1?ie=UTF8&refRID=1C1PNV9TYK1VN2KWT20A)想要搞图形个人认为必须从光线跟踪开始你才会认识到渲染的本质，这本书把所有关于渲染的知识都传授给你了，无论有多难都要硬着头皮啃完。
- [Ray Tracing from the Ground Up](http://www.amazon.cn/Ray-Tracing-from-the-Ground-Up-Suffern-Kevin/dp/1568812728/ref=sr_1_2?s=books&ie=UTF8&qid=1438618507&sr=1-2&keywords=Ray+Tracing+from+the+Ground+Up)如果你确实啃不动上面那本书，你就先看这本吧，有中文版《光线跟踪算法技术》

  上面那些书读完，相信渲染什么的你应经有了全面的了解了。

--------------------------------------------------------------------------------

# 动画与模拟
 有了渲染还不够，想一下《冰雪奇缘》中的雪是多么的真实，不光是视觉呈现上，形态上，结冰过程都非常真实；再比如游戏里面的物理，《古墓丽影9》的劳拉的"海飞丝"。这些东西的实现光靠渲染是肯定不行的，以为他们还具有物理真实性，动力学特诊等等，要在计算机里面做这些东西就叫做动画和模拟。

 动画模拟这部分东西很多很杂，而且对数学要求非常高，什么流体模拟动不动就是纳维斯托克斯方程，你说不懂这是什么意思？这个只是基本而已。笔者比较关注模拟这部分东西，曾经有个大神给我的入门书我列一下，看了就怕：
- Fluid simulation for computer graphics, by Robert Bridson
- Paper:stable fluids(stam99),visual simulation of smoke(ronFedkiw),practical animation of liquids(foster), Animating Suspended Particle Explosions(feldman), animating sand as fluids(Y. Zhu), A Fast Variational Framework for Accurate Solid-Fluid Coupling(Chris Batty). A parallel multigrid Poisson solver for fluids simulation on large grids(McAdams) A material point method for snow simulation(UCLA)
- Numerical Mathematics
- a first course in numerical methods
- Methods of computational fluid dynamics
- A multigrid tutorial
- vortex methods: theory and practice.
- mathematical theory of finite element method
- turbulent flow

> [知乎_张心欣_的回答](http://www.zhihu.com/question/29986665)

这么一大堆书不是危言耸听，模拟对于数学的要求的确很好，对于不同的模拟领域，你还要对那个领域有很深的了解。比如搞流体，你必须了解计算流体力学的一些东西，搞织物，你还要会打毛衣，等等等等，这取决于你想模拟什么。

然而对于普通的开发者你只需要拿一篇Paper能照着写出来就可以了。

这方面的入门书不是很多，我看过的概述类的有[《计算机动画算法与技术》](http://book.douban.com/subject/20255285/)

流体方面有《[Fluid Simulation for Computer Graphics》](http://book.douban.com/subject/2584523/)

其他的就是多关注一下siggraph paper，没事找几篇感兴趣的尝试做一做[参考](http://www.zhihu.com/question/29998274)

当然你数学一定要跟得上。

另外，我安利一下，如果大家对这方面感兴趣的话，可以在下半学期打听一下数字媒体学院有没有**张军**老师的`计算机动画编程`课程，笔者这方面就是他启蒙的，讲的非常好，有兴趣可以去蹭课 ^_^。

--------------------------------------------------------------------------------

# 游戏引擎
大家应该都听说过虚幻3，unity3D这些东西。都知道这些东西是游戏引擎，但情况并非如此，游戏引擎到底是什么呢？笔者用几句通俗易懂的话描述一下：

> 引擎这个词最早应该来源于汽车，汽车的引擎驱动汽车运动，是汽车的核心部分，所以游戏引擎自然可以理解为游戏的核心部分，驱动游戏运行。但是我认为，现在我们说的游戏引擎意义远非如此。 从历史角度说，最早的时候，人们想写一个游戏，于是他们从零开始写，然后他们想写第二个游戏，于是他们又从零开始写，写了很多个，最后发现这些代码里面频频有重复的公共代码，这些代码所有的游戏都用得上，于是那群人把这些代码抽出来写到一起做个库，以后开发游戏的时候直接用就好了。直到后来，游戏越做越复杂，这些代码也越来越复杂，出现所谓的渲染系统，声音系统，运行时对象系统等等，再后来有商人懂了脑经于是出现了什么虚幻，unity，起源。 游戏和游戏引擎之间并没有绝对的界限或者说的确在某些时候难以区分。所以我会说写游戏的代码，你都可以理解为游戏引擎，至于后来出现的什么脚本，事件流之类的，都是后来为了更加方便快速的开发，抽出来的。而这些东西底层还是那些最基本的代码，这些代码也可以说就是游戏引擎的一部分。 区分一下游戏引擎和游戏编辑器，你所熟知的unity，ue基本讲的看到的都是他们的editor，这些editor是为了加速工作流才出现的，如果把引擎和汽车引擎类比editor仅仅只是开发工具（造汽车工具，车床之类的）并非游戏引擎的一部分（因为游戏运行的时候，编辑器并没有运行），不过从游戏引擎是一件用来开发游戏的工具的角度来讲，他们也应该是游戏引擎的一部分。（说实话这个区分见仁见智） 更广泛的说，游戏开发说到底是一个巨大的软件工程，游戏引擎在其中扮演的就是工具和方法集的角色，而这些东西本身也来自游戏开发过程，所以好的游戏引擎一定来自游戏。 游戏引擎的目标是快速便捷优秀的完成游戏，它是一种工具和方法集，所以它会在一定程度上影响游戏的最终品质。比如说渲染比较底层，一般都是引擎代劳，开发者可以适当的控制，不同的引擎会使用不同的渲染方案，不同的渲染方案就会造成不同的渲染结果，最终反映在画面上的东西就不一样，帧率也有可能不一样等等，造成的体验自然不一样。 但是引擎对游戏质量的影响并不是绝对的。举个极端的例子，如果你叫一帮智障来使用起源2开发游戏，最终会出什么，什么都没有，而V社那帮人搞出了dota2。

提取上面这段话的重要部分，可以发现游戏引擎其实就是一堆用来创造游戏的通用代码。这样一来，我们如果定义：打印一个字符串就是一个游戏，那么printf函数从某种意义上就是"游戏引擎"。 然而事实上游戏比较复杂，有NPC，有场景，有声音等等东西。这些东西都需要管理，所以引擎里面会有管理这些东西的代码。 网上有很多人写了个能渲染东西的东西就说自己写了个游戏引擎，其实这样的说法有误，那个只能叫做渲染引擎，游戏引擎，特别是一个可用的游戏引擎是极其复杂的。他不仅要考虑质量还要考虑运行效率，除了这些开发效率等等更多的因素在一个成熟的引擎中都是极端重要的考量因素。所以，一个人想开发一个可用的大型游戏引擎是绝对不可能的。 然而这并不妨碍我们造轮子，我们可以写一些玩具引擎。笔者曾经写过2个玩具引擎，第一次写的时候啥都不懂，心比天高，扬言此引擎可以做任何游戏，跨四大平台，使用起来无比方便，但是直到写完，真正想要用得时候才发现，这就是一堆垃圾，根本无法使用，代码里面到处都是hdc，跨平台更是无从谈起。 一年后，笔者有了适用Unity的经验，第二次决定再写一个完整的游戏引擎，这一次写的之前看了很多书，包括《游戏引擎架构》《3D游戏编程大师》《Windows游戏编程大师技巧》《游戏编程精粹》所有非图形AI的内容，参考了unity，ue4，cocos2d等引擎，最后写了个基于Lua脚本的相对完善的2d引擎。然而当我再次想要适用的时候，我发现虽然勉强可以用，但是依然很不顺手，效率更是无从谈起，但是东西倒是学到不少。安利一下那个引擎现在开源了[github](https://github.com/wubugui/WIP). 说这些是为了告诉大家，如果大家对游戏引擎感兴趣随时都可以动手写，但是下面这些想法最好不要有
- "我要写一个跨时代的商业引擎"，有这种想法你会在执行过程中深受挫败，对于一个强迫症来说，你就永远也写不完你的引擎了。
- 一上来就扬言要跨几大平台，血与泪的教训，奉劝大家先完成一个核心，慢慢修改，不行推到重写，直到最后你就可以写出一个相对完善的东西，而且可以学到不少东西。
- 优化优化，现在就开始优化，这样你一辈子都写不完一个模块，现代的CPU还是可以承受住你写的那些代码的。

遇到什么问题推荐大家看看《游戏编程精粹1-8》，这个系列的书很好，惯有游戏编程的各种方案都有，虽然有的比较老，但是依然很有趣。还有一本书自然是《游戏引擎架构》了，这本书全面讲述了一个游戏引擎有的所有子系统组件，看完一定大有收获。

下面大概说一下一个游戏引擎中大家可能比较感兴趣的几个部分：

## 脚本
脚本说白了是这样一个过程：宿主语言call脚本语言call宿主语言提供的借口。说白点就是一个可以编程的配置文件。实现这个东西只要想办法将脚本语言中的对象和宿主语言中的对象对应起来就解决了一大半问题，至于优化，效率都是后话。不过现在的游戏开发，脚本也不是一个先进的东西了，UE4的blueprint事件流等等，虽然其实没什么卵用但图形化了也已经非常高端了。你可以选择的脚本语言可以有很多，Python，Lua甚至自己实现一门。这个方面可以参考《游戏脚本高级编程》这本书，里面描述了多数语言与c++的集成方案，最后自己实现了一门脚本语言，另外《游戏编程精粹》中也有不少主题是专门讲解脚本编程的。最后Unity3D的CS脚本可以反汇编了看一下。

## 骨骼动画
往一个游戏引擎中实现骨骼动画并不是一件难事，关键是你要有一个骨骼动画系统。2d的骨骼动画，有很多现有的实现比如Spine、dragonbone等等。而你自己写一个也不是难事，这可以参看计算机动画的支持。骨骼动画说到底是关节矩阵，手痒再加上IK复杂不到哪儿去。比较关键的是这些动画数据如何与原本的渲染数据绑定起来，如何有效的控制这些动画数据。这部分并没有一个用之四海皆准的方案，需要大家进一步去探索了。

## 跨平台
可能你也会想要做一个安卓上的游戏引擎。做这件事之前你需要先了解安卓上如何使用es渲染，如何播放声音等等，了解了之后跨平台代码的编写可以参考一下《C++跨平台开发技术指南》避免书写一些无移植性的代码。当然，你也可以选择一个良好的跨平台中间件。个人的经验是，上java......

**Comment by SimplyY** [comment]
学长好棒!

就是 github 要求的 markdown 格式比较严格，不过 atom 大法好，我先复制到 atom 再用插件tidy 了一下，然后复制过来，格式就 ok了

yeah

**Comment by semprathlon** [comment]
汽车人总动员2333

物理模型还真是那么回事

**Comment by SimplyY** [comment]
已链接 到了https://github.com/CoderUnion/coderunion.github.io/issues/39 这里
