### ISSUE TITLE
编程工具收集

### ISSUE THREAD

**Issue by SimplyY** [CoderUnion/coderunion.github.io#47]
这里记录一些编程工具吧，最近 atom 用的真心顺手

**Comment by SimplyY** [comment]
### 文档、博客必备
markdown简明教程： http://www.jianshu.com/p/7bd23251da0a 
程序员必备写文档、博客的排版利器（github全程支持readme、issue）


##### 然后本地编辑md的好软件有：
- win：markdown http://markdownpad.com/download.html
- osx： mou http://25.io/mou/  macdown： http://macdown.uranusjr.com/download/latest/


### 压缩图片 
压缩到1/4 就问你怕不怕。。。 
http://www.jpegmini.com/
https://tinypng.com/

**Comment by CodeFalling** [comment]
## 编辑器
![[spacemcas](https://github.com/syl20bnr/spacemacs)](https://github.com/syl20bnr/spacemacs/raw/master/doc/img/title2.png)


## 在线文档
http://devdocs.io/

**Comment by SimplyY** [comment]
## osx下
键盘流打法，所有当前界面的按键被映射到了文字
https://shortcatapp.com/

**Comment by reverland** [comment]
atom在linux下呵呵，我是懒得折腾

**Comment by SimplyY** [comment]
mac 特别棒啊，而且上个月才出的1.0稳定版
