### ISSUE TITLE
[投稿]几次失败的面试

### ISSUE THREAD

**Issue by NaturalL** [CoderUnion/coderunion.github.io#48]
好像网站上没啥人气啊，还是issues有人气。
http://naturall.github.io/2015/09/13/interview-experience/

**Comment by SimplyY** [comment]
笔记 issues watch 相当于 订阅了嘛，其实 issue 写博客也行。。

面试靠人品，，也需要准备看来，，看完我简直忧心忡忡啊 qaq

**Comment by SimplyY** [comment]
已引用

**Comment by reverland** [comment]
很棒啊觉得，周末赶着我也写写，才是被虐成汪。。。
