### ISSUE TITLE
关于社区方向

### ISSUE THREAD

**Issue by CodeFalling** [CoderUnion/coderunion.github.io#6]
在#4中@NaturalL提到关于投稿文章的基本要求，感觉有必要细化讨论，方便投稿者参考，在审核的时候也好有依据。

@xen0n @SimplyY @CoderUnion @NaturalL

以及请关心的人watch以下这个repo

**Comment by SimplyY** [comment]
我把之前@NaturalL 的回答在这里引用一下，方便我们继续讨论

> 我觉得这种具体的知识点没必要放上去，以下几项就行了：
原创文章 + 方向路线介绍（感受，学习方法） + 书籍推荐（理论） + 网站技术推荐（知识面、视野） + 项目推荐（实践）
下面的不能放上去：
受众太窄
遇到问题一google一百度就行的
一个学校，人不会很多。文章一定要精，实在、接地气，解困惑，拓视野。

**Comment by NaturalL** [comment]
以前上听雨，我从听雨上知道了 @xen0n 和 reverland，他们是很值得学习的人，最重要的是，我看到了他们对计算机的热情，让我很受鼓舞。

大学课堂教育是有很大欠缺的，大部分老师对计算机并没有热情，所以他们不会激发你的兴趣，也不会正确地引导你。
我们完全可以创造良好的氛围，弥补老师缺乏的热情。

对于这个网站，我觉得它应该成为一个索引，教你如何找到感兴趣、有价值的知识，如何找到值得学习的人；一个朋友或老师，交流、分享、协作、鼓励，找到好的学习方法，合适的技术路线，形成良好的氛围。

非常细的知识点，这种索引太细了，看完这篇文章就没了，不如推荐一个技术网站，或者一个牛人的博客。
前几天的投稿：“[Visual Studio]Windows窗体应用程序代码中的[STAThreadAttribute]是什么? ”，如果改成我在学习XX，我在做XX项目，我遇到XX问题，我是怎么解决这个问题的，那就非常不错，可以让大家学习你解决问题的方法，也可以让大家知道你在做什么，学什么，对什么感兴趣。而且这样更加生动有感染力。

**Comment by SimplyY** [comment]
> 大学课堂教育是有很大欠缺的，大部分老师对计算机并没有热情，所以他们不会激发你的兴趣，也不会正确地引导你。
> 我们完全可以创造良好的氛围，弥补老师缺乏的热情。

点赞~
这就是我想做的事~
像学弟@semprathlon 的投稿，其实以后可以弄个链接锦集的，当做一个进入相关知识的入口，比如windows 开发锦集（如果不是项目的话）。
如果是项目，那么学长的提议太棒了~
我们初期也是想过一起组队弄开源项目的，以后可以单独弄一个分类“项目”，然后里面挂着我们弄的项目，既是一种展示，也是一种引路，还可以吸引合作者或者讨论者~

**Comment by SimplyY** [comment]
> 原创文章 + 方向路线介绍（感受，学习方法） + 书籍推荐（理论） + 网站技术推荐（知识面、视野） + 项目推荐（实践）

其实我觉得这个已经很全了 @CodeFalling ，更细致的可以加上锦集文章（比如thinkinjava笔记心得，就可以按照内容在同一篇文章里放上很多博文链接，而不需要把知识碎片化，挡住一个分类的其他文章）总而言之避免知识碎片化~

**Comment by SimplyY** [comment]
已归档
